schema_version: 1

context:
  version: "26.4.17"

package:
  name: cppimport
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/cppimport/cppimport-${{ version }}.tar.gz
  sha256: 1fd9c1f16b2cf346507ef81b17f9b4947ddf0d5818b26f6c03078e8e7b366444

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools_scm
  run:
    - filelock
    - mako
    - pybind11
    - python >=${{ python_min }}
    - setuptools

tests:
  - python:
      imports:
        - cppimport
      pip_check: true
      python_version:
        - ${{ python_min }}.*
  - files:
      source:
        - tests
    requirements:
      run:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - pip
        - pytest
    script:
      - if: not win
        then: pytest -v tests/test_cppimport.py

about:
  summary: Import C++ directly from Python!
  description: |
    Sometimes Python just isn't fast enough. Or you have existing code in a C or C++ library. So, you write a Python extension module, a library of compiled code. I recommend pybind11 for C++ to Python bindings or cffi for C to Python bindings. I've done this a lot over the years. But, I discovered that my productivity is slower when my development process goes from Edit -> Test in just Python to Edit -> Compile -> Test in Python plus C++. So, cppimport combines the process of compiling and importing an extension in Python so that you can just run import foobar and not have to worry about multiple steps. Internally, cppimport looks for a file foobar.cpp. Assuming one is found, it's run through the Mako templating system to gather compiler options, then it's compiled and loaded as an extension module.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tbenthompson/cppimport

extra:
  recipe-maintainers:
    - minrk
